# Generated by Django 4.2.1 on 2024-06-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
